[package]
name = "okra"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.5"

[dependencies.windows]
features = [
    "Media_Ocr",
    "Graphics_Imaging",
    "Storage_Streams",
    "Foundation",
    "Graphics_Capture",
]
